# Dependencies
markdown:         kramdown
# highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Navigation links in the header of the website
navigation_items:
  Home:     '/'         # /index.html
  About:    '/about'    # /about.html
  Blog:     '/blog/'    # /blog/index.html
  # Projects: '/projects' # /projects.html
  # Talks:    '/talks'    # /talks.html
  # Resume:   '/resume'   # /resume.html
  # Archive:  '/archive'

# Setup
title:
  Wataru
  Suzuki
tagline:          'A Jekyll theme'
description:      'A Mobile app developer.'
url:              https://watarusuzuki.github.io/
baseurl:          /

author:
  name:           'Wataru Suzuki'
  url:            https://twitter.com/JchanKchan

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/WataruSuzuki/watarusuzuki.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
